export const data=[{
    id: "1",
    first_name: "Joann",
    last_name: "Whenham",
    email: "jwhenham0@angelfire.com",
    gender: "Female",
    ip_address: "60.245.120.40"
  }, {
    id: "2",
    first_name: "Ximenes",
    last_name: "Linthead",
    email: "xlinthead1@opensource.org",
    gender: "Male",
    ip_address: "151.122.179.8"
  }, {
    id: "3",
    first_name: "Corissa",
    last_name: "Godball",
    email: "cgodball2@phoca.cz",
    gender: "Polygender",
    ip_address: "227.61.68.208"
  }, {
    id: "4",
    first_name: "Harley",
    last_name: "Donegan",
    email: "hdonegan3@answers.com",
    gender: "Female",
    ip_address: "17.236.150.199"
  }, {
    id: "5",
    first_name: "Joanie",
    last_name: "Coupar",
    email: "jcoupar4@youtube.com",
    gender: "Female",
    ip_address: "243.62.127.120"
  }, {
    id: "6",
    first_name: "Karin",
    last_name: "Ambroz",
    email: "kambroz5@123-reg.co.uk",
    gender: "Female",
    ip_address: "73.59.158.100"
  }, {
    id: "7",
    first_name: "Edsel",
    last_name: "Tysack",
    email: "etysack6@vistaprint.com",
    gender: "Male",
    ip_address: "186.70.118.117"
  }, {
    id: "8",
    first_name: "Chucho",
    last_name: "Dumphy",
    email: "cdumphy7@ihg.com",
    gender: "Male",
    ip_address: "8.137.50.31"
  }, {
    id: "9",
    first_name: "Annemarie",
    last_name: "Juliff",
    email: "ajuliff8@eventbrite.com",
    gender: "Female",
    ip_address: "236.204.171.197"
  }, {
    id: "10",
    first_name: "Gabriello",
    last_name: "Linster",
    email: "glinster9@github.io",
    gender: "Male",
    ip_address: "112.74.254.105"
  }]